### ISSUE TITLE
Wrong conditions in slot `pizza_size`

### ISSUE THREAD

**Issue by lamducanhndgv** [RasaHQ/conversational-ai-course-3.x#4]
Source code in [tutorial](https://github.com/RasaHQ/conversational-ai-course-3.x/tree/main/video-09-2-custom-forms) has a mistake. 

The conditions of slot mapping of `pizza_type` in current `domain.yml` file: 
```yaml
pizza_size:
  type: text
  influence_conversation: true
  mappings:
  - type: from_entity
    entity: pizza_size
    conditions:
    - active_loop: pizza_form
      requested_slot: pizza_size
```

This condition will cause slot `pizza_size` is never filled. Condition should be fixed as the following:

```yaml
pizza_size:
    type: text
    influence_conversation: true
    mappings:
      - type: from_entity
        entity: pizza_size
        conditions:
          - active_loop: simple_pizza_form
            requested_slot: pizza_size
          - active_loop: fancy_pizza_form
            requested_slot: pizza_size
```
